### ISSUE TITLE
Suggestion: Add AppImage release

### ISSUE THREAD

**Issue by rj-jesus** [naelstrof/maim#213]
Would you consider creating an AppImage for `maim`?

Here's a sample `maim.yml` recipe that repackages the Ubuntu package:
```yml
app: maim
union: true

ingredients:
  dist: focal
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ focal main universe

script:
  - cat > maim.desktop <<\EOF
  - [Desktop Entry]
  - Encoding=UTF-8
  - Name=maim
  - Comment=Make Image
  - Exec=maim
  - Type=Application
  - Icon=maim
  - Categories=Utility
  - EOF
  - touch maim.png
```

It can be used with [`pkg2appimage`](https://github.com/AppImage/pkg2appimage). The resulting AppImage seems to work properly.
